markdown: kramdown
kramdown:
  input: GFM
redcarpet:
  extensions: ['tables']
name: OrigoDB Blog
description: Build faster systems faster using OrigoDB, an in-memory database for NET/Mono.
url: http://origodb.com/blog
exclude: ['build-docs.pl']
